cdssweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^hypertension/', include('hypertension.urls', namespace="hypertension")),
]

hypertension/urls.py
from django.conf.urls import url
from hypertension import views

urlpatterns = [
	url(r'^$', views.SimpleView.as_view(), name='Simple'),

]

hypertension/models.py
from django.db import models


# Create your models here.

class Disease(models.Model):
	name = models.CharField(max_length=200, unique=True)
	
	def __str__(self):
		return self.name
		

class DrugType(models.Model):
	name = models.CharField(max_length=20, unique=True)
	
	def __str__(self):
		return self.name
		
class SideEffect(models.Model):
	name = models.CharField(max_length=20, unique=True)
	
	def __str__(self):
		return self.name

class Score(models.Model):
	score = models.FloatField()
	title = models.CharField(max_length=50, unique=True)
	description = models.TextField()
	
	def __str__(self):
		return self.title
	
class Disease_DrugType_Score(Score):
	disease = models.ForeignKey(Disease)
	drugType = models.ForeignKey(DrugType)
		
class DrugType_DrugType_Score(Score):
	drugTypeA = models.ForeignKey(DrugType, related_name='drugTypeA')
	drugTypeB = models.ForeignKey(DrugType, related_name='drugTypeB')
	
class SideEffect_DrugType_Score(Score):
	sideEffect = models.ForeignKey(SideEffect)
	drugType = models.ForeignKey(DrugType)
	

hypertension/views.py
from django.shortcuts import render
from django.views import View
from hypertension.models import Disease, DrugType, SideEffect, Score, Disease_DrugType_Score, DrugType_DrugType_Score, SideEffect_DrugType_Score


# My own class

class ResultList():
	drugtype = "drugtype"
	description = "drug description"
	classification = "drug class"
	def __init__(self, drugtype=None, description=None, classification=None):
		self.drugtype = drugtype
		self.description = description
		self.classification = classification
	
# Create your views here.

class SimpleView(View):
	
	template_name = 'hypertension/hypertension_simple.html'
	context = {}
	drugScore = []
	drugName = []
	drugDescription = []
	drugClass = []
	drugtype_number = 5
	
	def get_default_context_data(self):
		self.context['object_list'] = ['Disease', 'DrugType', 'SideEffect']
		self.context['disease_list'] = Disease.objects.all()
		self.context['drugtype_list'] = DrugType.objects.all()
		self.context['sideeffect_list'] = SideEffect.objects.all()
		self.context['result_list'] = self.makeRecommendation()

	
	def get_selected_content_data(self, request):
		if 'disease' in request.POST:
			self.context['disease_selectedlist'] = dict(request.POST)['disease']
		if 'drugtype' in request.POST:
			self.context['drugtype_selectedlist'] = dict(request.POST)['drugtype']
		if 'sideeffect' in request.POST:
			self.context['sideeffect_selectedlist'] = dict(request.POST)['sideeffect']
	
	def get(self, request, *args, **kwargs):
		self.initialize (request)
	
		return render(request, self.template_name, self.context)
		
	def post(self, request, *args, **kwargs):
		self.initialize(request)
		
		return render(request, self.template_name, self.context) 
	
	def initialize(self, request):
		self.context = {}
		self.drugtype_number = 5
		self.drugInitialize()
		self.get_selected_content_data(request)
		self.get_default_context_data()
		
	def makeRecommendation(self):
		
		result = []
		if 'disease_selectedlist' in self.context:
			self.multiplyDiseaseDrugType(self.context['disease_selectedlist'])
		if 'drugtype_selectedlist' in self.context:
			self.multiplyDrugTypeDrugType(self.context['drugtype_selectedlist'])
		if 'sideeffect_selectedlist' in self.context:
			self.multiplySideEffectDrugType(self.context['sideeffect_selectedlist'])
			
		for i in range(self.drugtype_number):
			print (self.drugScore[i])
			if self.drugScore[i] > 1:
				self.drugClass[i] = 'class A'
			if self.drugScore[i] == 1:
				self.drugClass[i] = 'class B'
			if self.drugScore[i] < 1:
				self.drugClass[i] = 'class C'
			
			result.append(ResultList(self.drugName[i], self.drugDescription[i], self.drugClass[i]))
		
		
		return result
	
	def multiplyDiseaseDrugType(self, disease_list):
		for list in Disease_DrugType_Score.objects.all():
			for disease in disease_list:
				if str(getattr(list, 'disease')) == disease:
					
					for i in range(self.drugtype_number):
						if self.drugName[i] == getattr(list, 'drugType'):
							
							self.drugScore[i] *= getattr(list, 'score')
							self.drugDescription[i] += getattr(list, 'description') + "<br>"
	
	def multiplyDrugTypeDrugType(self, drugtype_list):
		for list in DrugType_DrugType_Score.objects.all():
			for drugtype in drugtype_list:
				if str(getattr(list, 'drugTypeB')) == drugtype:
					
					for i in range(self.drugtype_number):
						if self.drugName[i] == getattr(list, 'drugTypeA'):
							
							self.drugScore[i] *= getattr(list, 'score')
							self.drugDescription[i] += getattr(list, 'description') + "<br>"

	def multiplySideEffectDrugType(self, sideeffect_list):
		for list in sideeffect_list:
			for i in range(self.drugtype_number):
				print (list, self.drugName[i])
				print (type(list), type(self.drugName[i]))
				if str(self.drugName[i]) == list:	
					self.drugScore[i] *= 0.1
					self.drugDescription[i] += list + "에 부작용이 있음" + "<br>"
	
	def drugInitialize(self):
		self.drugScore = [1 for _ in range(self.drugtype_number)]
		self.drugName = ["" for _ in range(self.drugtype_number)]
		self.drugDescription = ["" for _ in range(self.drugtype_number)]
		self.drugClass = ["" for _ in range(self.drugtype_number)]
		
		for i in range(self.drugtype_number):
			self.drugName[i] = DrugType.objects.all()[i]
		

hypertension/templates/hypertension/hypertension_simple.html
<!DOCTYPE html>
<html>
<head>
	<style>
		.flex-container {
			display: flex;
			flex-flow: row wrap;
			text-align: center;
		}

		.flex-container > * {
			padding: 15px;
			flex: 1 100%;
		}

		.select {
			text-align: center;
		}
		.select > * {
			border-bottom: 1px solid #eee;
			padding: 10px;
		}

		.result {
			
			text-align: left;
		}
		.result > * {
			
			padding: 10px;
		}

		header {background: black;color:white;}
		footer {background: #aaa;color:white;}
		


		@media all and (min-width: 1000px) {
			.select {
				text-align:center;
				flex:1;
				order:1;
			}
			.result {
				flex:1;
				order:2;
			}
			footer {
				order:3;
			}
		}
		
		
		
		.labelbox {
			text-align:left;
			color: #333;
			display: inline-block;
			width: 40%;
			padding: 3px;
			font-size: 18px;
		}
		.labeltitle {
			text-align:left;
			color: #333;
			display: inline-block;
			width: 100%;
			padding: 3px;
			font-size: 18px;		
		}
		.textbox {
			display: inline-block;
			vertical-align: text-top;
			border-radius: 4px;
			width: 295px;
		}
		.related-widget-wrapper {
			display: inline-block;
			vertical-align: text-top;
			border-radius: 4px;
		
		}

		input, select {
			display: inline-block;
			box-sizing: border-box;
			border-radius: 4px;
			border-style: solid;
		}
		#id_disease {
			height: 250px;
			width: 300px;
		}
		#id_drug {
			height: 84px;
			width: 300px;
		}
		
		#id_sideeffect {
			height: 84px;
			width: 300px;
		}
		
		table, th, td { 
			
			text-align: left;
			padding: 4px;
			font-size: 18px;
			color: #79aec8;
			
		}
		table {
			width: 100%;
		}
		th, td {
			vertical-align: text-top;
			border-bottom: 1px solid #eee;
		}
		th {
			flex: 1;
			order: 1;
			width: 30%;
		}
		td {
			flex: 2;
			order: 2;
			width: 70%;
			text-align: right;
		}
		td > * {
			font-size: 18px;
			color: #79aec8;
			text-decoration: none;
		}
		caption {
			padding: 4px;
			text-align: left;
			font-size: 18px;
			font-weight: 400;
			color: #fff;
			width: 300 px;
			background: #79aec8;
		}
		.detail {
			color: #000000;
		}
		.submit-row {
			padding: 12px 14px;
			margin: 0 0 20px;
			background: #f8f8f8;
			border: 1px solid #eee;
			border-radius: 4px;
			text-align: right;
			overflow: hidden;
		}
		.submit-row input {
			height: 35px;
			line-height: 15px;
			margin: 0 0 0 5px;
		}

		.submit-row input.default {
			margin: 0 0 0 8px;
			text-transform: uppercase;
		}

	</style>
	<script language="javascript">
		function toggle(number) {

			var ele = document.getElementById("toggleText" + number.toString());
			var text = document.getElementById("displayText" + number.toString());
			if(ele.style.display == "block") {
				ele.style.display = "none";
				text.innerHTML = "Reason for classification";
			}
			else {
				ele.style.display = "block";
				text.innerHTML = "Hide reason";
			}		
		}
	</script>
</head>
<body>

	<div class="flex-container">
		<header>
		  <h1>HyperDoctor</h1>
		</header>
		
		<main class="select">
			<div class="select-selected">
	
				<label class="labelbox">Summary of patient information:</label>
				
				<textarea class="textbox" rows="10" cols="40">
{% if disease_selectedlist %}Disease:{% for disease_name in disease_selectedlist %}
  {{ disease_name }} {% endfor %}
				{% endif %}
{% if drugtype_selectedlist %}Drug:{% for drugtype_name in drugtype_selectedlist %}
  {{ drugtype_name }} {% endfor %}
				{% endif %}
{% if sideeffect_selectedlist %}Side Effect:{% for sideeffect_name in sideeffect_selectedlist %}
  {{ sideeffect_name }} {% endfor %}
				{% endif %}				
				
	
				</textarea>
			
			</div>
			
			<div class="select-selected">
			
				<label class="labelbox">Disease:</label>
				
				<div class="related-widget-wrapper">
					<select multiple class="textbox" id="id_disease" name="disease" form="complete">
						
						{% for disease_name in disease_list %}
						<option value="{{ disease_name }}">{{ disease_name }}</option>
						{% endfor %}
					</select>
				</div>	
			</div>
			<div class="select-selected">
			
				<label class="labelbox">Drug:</label>
				
				<div class="related-widget-wrapper">
					<select multiple class="textbox" id="id_drug" name="drugtype" form="complete">

						{% for drugtype_name in drugtype_list %}
						<option value="{{ drugtype_name }}">{{ drugtype_name }}</option>
						{% endfor %}
					</select>
				</div>	
			</div>	
			<div class="select-selected">
			
				<label class="labelbox">Side Effect:</label>
				
				<div class="related-widget-wrapper">
					<select multiple class="textbox" id="id_sideeffect" name="sideeffect" form="complete">

						{% for sideeffect_name in sideeffect_list %}
						<option value="{{ sideeffect_name }}">{{ sideeffect_name }}</option>
						{% endfor %}
					</select>
				</div>	
			</div>	
						

			<form = "" method = "post" id = "complete"> {% csrf_token %}
				<div class="submit-row">
					<input type="submit" value="Complete" />
				</div>
			</form>
		</main>	

		<main class="result">
			<div>
				<label class="labeltitle">Hypertension management guideline recommendation</label>
				<br>
				<br>

				<table>
						
					<caption>
						Highly recommended drugs
					</caption>

					{% for result in result_list %}
					{% if result.classification == "class A" %}
					<tr>
						<th>
							{{ result.drugtype }}
						</th>
						<td>
							<a id="displayText{{ forloop.counter }}" href="javascript:toggle({{ forloop.counter }});">
								Reason for classification
							</a>
							<div id="toggleText{{ forloop.counter }}" style="display: none">
								<a class="detail">
									{% autoescape off %}
									{{ result.description }}
									{% endautoescape %}
								</a>
							</div>
						</td>
					</tr>

					
					{% endif %}

					{% endfor %}
					
				</table>
				<table>
										
					<caption>
						Recommended drugs
					</caption>

					{% for result in result_list %}
					{% if result.classification == "class B" %}
					<tr>
						<th>
							{{ result.drugtype }}
						</th>
						<td>
							<a id="displayText{{ forloop.counter }}" href="javascript:toggle({{ forloop.counter }});">
								Reason for classification
							</a>
							<div id="toggleText{{ forloop.counter }}" style="display: none">
								<a class="detail">
									{% autoescape off %}
									{{ result.description }}
									{% endautoescape %}
								</a>
							</div>
						</td>
					</tr>

					
					{% endif %}

					{% endfor %}
					
				</table>
				<table>
										
					<caption>
						Non-recommended drugs
					</caption>

					{% for result in result_list %}
					{% if result.classification == "class C" %}
					<tr>
						<th>
							{{ result.drugtype }}
						</th>
						<td>
							<a id="displayText{{ forloop.counter }}" href="javascript:toggle({{ forloop.counter }});">
								Reason for classification
							</a>
							<div id="toggleText{{ forloop.counter }}" style="display: none">
								<a class="detail">
									{% autoescape off %}
									{{ result.description }}
									{% endautoescape %}
								</a>
							</div>
						</td>
					</tr>

					
					{% endif %}

					{% endfor %}
					
				</table>
			</div>

		</main>
		  




		<footer>Copyright © HyperDoctor</footer>
	</div>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lange="en">
	<head>
		{% load static %}
		<link rel="stylesheet" href="{% static "admin/css/base.css" %}" />
		<title>{% block title %}CDSS{% endblock %}</title>
	</head>

	<body>
		<div id="sidebar">
			{% block sidebar %}
			<ul>
				<li><a href="/">CDSS_Home</a></li>
				<li><a href="/admin/">Admin</a></li>
			</ul>
			{% endblock %}
			<br>
		</div>
		
		<div id="content">
			{% block content %}{% endblock %}
		</div>
	</body>
</html>
			

templates/base_hypertension.html
{% extends "base.html" %}

<title>{% block title %}Hypertension Application Site{% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
	<li><a href="/hypertension/">Hypertension_Home</a></li>
	
</ul>
{% endblock %}